/// `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod favorited_recipes;
pub mod followed_users;
pub mod grocery_lists;
pub mod liked_recipes;
pub mod pantries;
pub mod recipes;
pub mod sessions;
pub mod subscriptions;
pub mod users;


// ======================================================================
// SQLx FromRow compatibility structs
// ======================================================================

#[derive(Clone, Debug, sqlx::FromRow, serde::Serialize, serde::Deserialize)]
pub struct RecipeRow {
    pub id: String,
    pub owner_id: String,
    pub title: String,
    pub cuisine: String,
    pub cook_time_minutes: i32,
    pub ingredients: String,
    pub instructions: String,
    pub description: Option<String>,
    pub history: Option<String>,
    pub substitutions: Option<String>,
    pub allergens: Option<String>,
    pub image_url: Option<String>,
    pub images: Option<String>,
    pub updated_at: String,
    pub created_at: String,
}

#[derive(Clone, Debug, sqlx::FromRow, serde::Serialize, serde::Deserialize)]
pub struct UserRow {
    pub id: String,
    pub username: String,
    pub email: String,
    pub password_hash: String,
    pub display_name: String,
    pub theme: String,
    pub allergens: Option<String>,
    pub pantry_tracking_enabled: i32,
    pub last_connection_date: Option<String>,
    pub updated_at: String,
    pub created_at: String,
}
