/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface favoritesRow {
  'created_at': string;
  'recipe_id'?: string;
  'user_id'?: string;
}
export interface recipesRow {
  'allergens'?: string | null;
  'cook_time_minutes': number;
  'created_at': string;
  'cuisine': string;
  'description'?: string | null;
  'history'?: string | null;
  'id'?: string;
  'image_url'?: string | null;
  'images'?: string | null;
  'ingredients': string;
  'instructions': string;
  'owner_id': string;
  'substitutions'?: string | null;
  'title': string;
}
export interface usersRow {
  'created_at': string;
  'id'?: string;
  'username': string;
}
