/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface FavoritesRow {
  'created_at': string;
  'recipe_id'?: string;
  'user_id'?: string;
}
export interface FullRecipeViewRow {
  'allergens'?: string | null;
  'cook_time_minutes'?: number | null;
  'created_at'?: string | null;
  'cuisine'?: string | null;
  'description'?: string | null;
  'favorites_count'?: any | null;
  'history'?: string | null;
  'id'?: string | null;
  'image_url'?: string | null;
  'images'?: string | null;
  'ingredients'?: string | null;
  'instructions'?: string | null;
  'likes_count'?: any | null;
  'owner_id'?: string | null;
  'substitutions'?: string | null;
  'title'?: string | null;
  'updated_at'?: string | null;
}
export interface GroceryListsRow {
  'created_at': string;
  'id'?: string;
  'items': string;
  'owner_id': string;
  'title'?: string;
  'updated_at': string;
}
export interface LikesRow {
  'created_at': string;
  'recipe_id'?: string;
  'user_id'?: string;
}
export interface PantryRow {
  'created_at': string;
  'id'?: string;
  'ingredients': string;
  'owner_id': string;
  'updated_at': string;
}
export interface PublicFullUserViewRow {
  'allergens'?: string | null;
  'created_at'?: string | null;
  'display_name'?: string | null;
  'id'?: string | null;
  'last_connection_date'?: string | null;
  'recipe_count'?: any | null;
  'subscription_status'?: any | null;
  'subscription_tier'?: any | null;
  'theme'?: string | null;
  'total_likes_received'?: any | null;
  'updated_at'?: string | null;
  'username'?: string | null;
}
export interface RecipesRow {
  'allergens'?: string | null;
  'cook_time_minutes': number;
  'created_at': string;
  'cuisine': string;
  'description'?: string | null;
  'history'?: string | null;
  'id'?: string;
  'image_url'?: string | null;
  'images'?: string | null;
  'ingredients': string;
  'instructions': string;
  'owner_id': string;
  'substitutions'?: string | null;
  'title': string;
  'updated_at': string;
}
export interface SessionsRow {
  'access_token': string;
  'created_at': string;
  'expires_at': string;
  'id'?: string;
  'refresh_token': string;
  'updated_at': string;
  'user_id': string;
}
export interface SubscriptionsRow {
  'activity_status'?: string;
  'created_at': string;
  'current_period_end'?: string | null;
  'id'?: string;
  'stripe_customer_id'?: string | null;
  'stripe_subscription_id'?: string | null;
  'tier'?: string;
  'updated_at': string;
  'user_id': string;
}
export interface UsersRow {
  'allergens'?: string | null;
  'created_at': string;
  'display_name': string;
  'email': string;
  'id'?: string;
  'last_connection_date'?: string | null;
  'pantry_tracking_enabled'?: number;
  'password_hash': string;
  'theme'?: string;
  'updated_at': string;
  'username': string;
}
