//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod favorited_recipes;
pub mod followed_users;
pub mod grocery_lists;
pub mod liked_recipes;
pub mod pantries;
pub mod recipes;
pub mod sessions;
pub mod subscriptions;
pub mod users;
