#![allow(unused_imports)]
//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::favorited_recipes::Entity as FavoritedRecipes;
pub use super::followed_users::Entity as FollowedUsers;
pub use super::grocery_lists::Entity as GroceryLists;
pub use super::liked_recipes::Entity as LikedRecipes;
pub use super::pantries::Entity as Pantries;
pub use super::recipes::Entity as Recipes;
pub use super::sessions::Entity as Sessions;
pub use super::subscriptions::Entity as Subscriptions;
pub use super::users::Entity as Users;
