//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use ts_rs::TS;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, TS)]
#[sea_orm(table_name = "users")]
#[ts(export, export_to = "dto/user.ts", rename = "UserDTO")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", unique)]
    pub username: String,
    #[sea_orm(column_type = "Text", unique)]
    pub email: String,
    #[sea_orm(column_type = "Text")]
    pub password_hash: String,
    #[sea_orm(column_type = "Text")]
    pub display_name: String,
    #[sea_orm(column_type = "Text")]
    pub theme: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub allergens: Option<String>,
    pub pantry_tracking_enabled: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_connection_date: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::favorited_recipes::Entity")]
    FavoritedRecipes,
    #[sea_orm(has_many = "super::grocery_lists::Entity")]
    GroceryLists,
    #[sea_orm(has_many = "super::liked_recipes::Entity")]
    LikedRecipes,
    #[sea_orm(has_one = "super::pantries::Entity")]
    Pantries,
    #[sea_orm(has_many = "super::recipes::Entity")]
    Recipes,
    #[sea_orm(has_many = "super::sessions::Entity")]
    Sessions,
    #[sea_orm(has_one = "super::subscriptions::Entity")]
    Subscriptions,
}

impl Related<super::favorited_recipes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FavoritedRecipes.def()
    }
}

impl Related<super::grocery_lists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroceryLists.def()
    }
}

impl Related<super::liked_recipes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LikedRecipes.def()
    }
}

impl Related<super::pantries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pantries.def()
    }
}

impl Related<super::recipes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Recipes.def()
    }
}

impl Related<super::sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sessions.def()
    }
}

impl Related<super::subscriptions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subscriptions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
